#!/bin/bash

TESTS_PATHS='packages/*/tests/test*.lua  tests/test*.lua'
LIB_PATHS='tests/fakes/?.lua;packages/lime-system/files/usr/lib/lua/?.lua;packages/safe-upgrade/files/usr/sbin/?;;'

# create a temporaty script file to be able to run multiple commands inside docker
temp_file=$(mktemp /tmp/lime_test.XXXX)
trap "rm -f ${temp_file}" 0 2 3 15
chmod +x ${temp_file}

cat > ${temp_file}<< SCRIPT
#!/bin/bash
busted -v --coverage ${TESTS_PATHS} --lpath='${LIB_PATHS}' ${1} && luacov
SCRIPT

./tools/dockertestshell "${temp_file}"
